In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [3]:
nba_df = pd.read_csv("/content/drive/My Drive/DEEP Project/2012-18_officialBoxScore.csv")
nba_df.head()

       gmDate gmTime  seasTyp  ... opptSTL/TO     poss     pace
0  2012-10-30  19:00  Regular  ...    33.3333  88.9409  88.9409
1  2012-10-30  19:00  Regular  ...    33.3333  88.9409  88.9409
2  2012-10-30  19:00  Regular  ...    33.3333  88.9409  88.9409
3  2012-10-30  19:00  Regular  ...    84.6154  88.9409  88.9409
4  2012-10-30  19:00  Regular  ...    84.6154  88.9409  88.9409

[5 rows x 119 columns]

In [4]:
nba_df.describe()

            teamMin    teamDayOff  ...          poss          pace
count  44284.000000  44284.000000  ...  44284.000000  44284.000000
mean     241.794576      1.939730  ...     95.573082     94.873836
std        7.616808      1.070765  ...      5.816793      5.162873
min      226.000000      0.000000  ...     77.561700     76.996500
25%      240.000000      1.000000  ...     91.598400     91.331700
50%      240.000000      2.000000  ...     95.195600     94.764000
75%      240.000000      2.000000  ...     98.981400     98.266600
max      341.000000     11.000000  ...    131.144300    121.656400

[8 rows x 104 columns]

We need some dummy multivariable linear regression model template for the actual project. 

Let's use 2-Point % Made and 3-Point Made as our x-variable to predict Field Goal Percentage Made, our y-variable. 

The results should demonstrate some clear trends.

In [7]:
x = nba_df[["team2P%", "team3P%", "teamFT%", "teamOREB%"]]
y = nba_df["teamFG%"]

Need to split into training data and testing data

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
coeff_df = pd.DataFrame(regressor.coef_, x.columns, columns=['Coefficient'])
coeff_df

           Coefficient
team2P%       0.673280
team3P%       0.250563
teamFT%      -0.000426
teamOREB%     0.000235

Time to make our own predictions!

In [12]:
y_pred = regressor.predict(x_test)

In [14]:
actual_vs_prediction_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
actual_vs_prediction_df

       Actual  Predicted
38373  0.4321   0.446128
39947  0.4810   0.480642
40949  0.5000   0.503635
11780  0.3973   0.399536
37617  0.4744   0.484651
...       ...        ...
17934  0.4433   0.446760
13608  0.4396   0.438630
355    0.4444   0.443388
44212  0.4066   0.443676
41596  0.4940   0.562240

[8857 rows x 2 columns]

Let's analyze the errors!

In [15]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.010426277627599059
Mean Squared Error: 0.0002250866670503959
Root Mean Squared Error: 0.015002888623541665

The result is pretty expected since a prediction of FG% based on 2P% and 3P% should pretty much be error free.